int _putchar (char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int _strlen_recursion(char *len);
int palindrome(char *txt, int ini, int end);
int _check_asterisk(char *s3, int end_1);
int _equal_no_aster(char *s4, char *s5, int cont_2);
int identical_asterisk(char *s6, char *s7, int cont_3, int cont_4);
